const speciesPhotos: Record<string, any> = {
  pike:          require("../assets/fishicons/pike.png"),
  perch:         require("../assets/fishicons/perch.png"),
  carp:          require("../assets/fishicons/carp.png"),
  pikeperch:     require("../assets/fishicons/pikeperch.png"),
  forel:         require("../assets/fishicons/Rainbow_Trout.png"),
  zhereh:        require("../assets/fishicons/zhereh.png"),
  bass:          require("../assets/fishicons/Largemouth_Bass.png"),
  black_sea_bass: require("../assets/fishicons/blackseabass.png"),
  stripedbass:   require("../assets/fishicons/Striped_Bass.png"),
  nalim:         require("../assets/fishicons/Burbot.png"),
  losos:         require("../assets/fishicons/salmon.png"),
  sazan:         require("../assets/fishicons/sazan.png"),
  som:           require("../assets/fishicons/som.png"),
  sudak:         require("../assets/fishicons/sudak.png"),
  karas:         require("../assets/fishicons/Crucian_Carp.png"),
  kambala:       require("../assets/fishicons/European_Flounder.png"),
  tarpon:        require("../assets/fishicons/Tarpon.png"),
  kharius:       require("../assets/fishicons/European_Grayling.png"),
  sterlyad:      require("../assets/fishicons/Sterlet.png"),
  brook_trout:   require("../assets/fishicons/Brook_Trout.png"),
  bull_shark:    require("../assets/fishicons/Bull_Shark.png"),
  lake_sturgeon: require("../assets/fishicons/Lake_Sturgeon.png"),
  pagr:          require("../assets/fishicons/porgy.png"),
  bluefish:      require("../assets/fishicons/bluefish.png"),
  false_albacore: require("../assets/fishicons/falsealbie.png"),
  atlantic_mackerel: require("../assets/fishicons/Atlantic_Mackerel.png"),
  dogfish:       require("../assets/fishicons/Dogfish.png"),
  goby:          require("../assets/fishicons/Round_Goby.png"),
  golavl:        require("../assets/fishicons/Chub.png"),
  krasnoperka:   require("../assets/fishicons/Common_Rudd.png"),
  amur:          require("../assets/fishicons/Grass_Carp.png"),
  peskar:        require("../assets/fishicons/Gudgeon.png"),
  yaz:           require("../assets/fishicons/Ide.png"),
  gustera:       require("../assets/fishicons/Silver_Bream.png"),
  lin:           require("../assets/fishicons/Tench.png"),
};

export default speciesPhotos;
